apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.shortname" . }}-graphql-api-configmap
  labels:
    {{- include "graphql-api.labels" . | nindent 4 }}
data:
  SERVER_PORT: "9090"
  API_BASE_PATH: "/api"
  POSTGRES_HOST: "{{ template "app.shortname" . }}-postgresql"
  POSTGRES_PORT: "{{ .Values.postgresql.service.port }}"
  POSTGRES_USER: "{{ .Values.postgresql.global.postgresql.postgresqlUsername }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.global.postgresql.postgresqlPassword }}"
  POSTGRES_DB: "{{ .Values.postgresql.global.postgresql.postgresqlDatabase }}"
  JWT_SECRET: "R1BYcTVXVGNDU2JmWHVnZ1lnN0FKeGR3cU1RUU45QXV4SDJONFZ3ckhwS1N0ZjNCYVkzZ0F4RVBSS1UzRENwRw=="
  JWT_EXPIRATIONMS: "2592000000"
  ADMIN_USER: "admin"
  ADMIN_PASS: "P@ssword"
  ACTIVE_PROFILE: "prod"