apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.shortname" . }}-postgesql-secret
  labels:
    {{- include "graphql-api.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.postgresql.global.postgresql.postgresqlUsername | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.postgresql.global.postgresql.postgresqlPassword | b64enc | quote }}
